### ISSUE TITLE
Use with bulk RNAseq

### ISSUE THREAD

**Issue by kayserb** [phillipnicol/scGBM#1]
Great looking method Phillip! I've had a lot of success with GLM-PCA for bulk RNAseq experiments where I need to adjust for batches or other simple covariates. 

Think there would be any problems running scGMB on bulk data? I'm thinking studies with 50 to 100+ samples. Not sure if there is a lower sample limit needed.

**Comment by phillipnicol** [comment]
It should run the same, let me know if you have any problems. Can only adjust for categorical covariates (like known batch), can not control for continuous variables. 

The question would be if the Poisson sampling assumption is reasonable for your bulk RNA-seq data. A negative binomial model (which we do not offer) might be more appropriate.

**Comment by kayserb** [comment]
Thanks for the quick response - will let you know of any problems!
