### ISSUE TITLE
Continuous covariate

### ISSUE THREAD

**Issue by PierreBSC** [phillipnicol/scGBM#6]
Hi,

Thanks a lot for developing this really nice tool. I was wondering whether it would be possible to add a continuous covariate in addition to the batch vector ? I looked into the code but it seems that it is not directly doable.... Do you plan to add this as a new feature ?
Thanks a lot,
Best 
Pierre

**Comment by phillipnicol** [comment]
Hi Pierre,

Thank you! It is not something that is currently implemented, but if you are interested I think it would be pretty straightforward to add. 

Just to double check, you have a continuous covariate for each cell that you want to regress out in the model?

**Comment by PierreBSC** [comment]
Hi Phillip,
Thanks for the quick answer. Yes indeed for what I have in mind there would be one covariate value for each individual cell and that would act as general 'scaling factor'.
Thanks !

**Comment by phillipnicol** [comment]
Hi Pierre,

I have written a (unoptimized) prototype to fit the scGBM model with continuous cell-level covariates. This should work okay if the dataset you are using is not particularly large, but if you need it go faster please let me know, there are many ways to speed it up. 

Because a trick was used in the case of categorical/binary covariates, I wrote a new function called `gbm.cell.covariate()` that takes as input a cell covariate matrix `X.cov` with J (number of cell) rows and K (number of cell covariates, including intercept) columns. Please try the following demo to see how it works (here I use a factor as one of the "covariates"): 

```
set.seed(1)

#Install package from development branch
devtools::install_github("phillipnicol/scGBM", ref="cell_covariates")

I <- 500
J <- 1000

#Simulate a model with 500 genes, 1000 cells, and 10 true factors
sim <- scGBM::simData(I=I,J=J,d=10)

Y <- sim$Y

#Here we will pretend that the first true factor is a known cell covariate
X.cov <- model.matrix(Y[1,] ~ sim$V[,1])

#Notice that the model matrix should include an intercept
head(X.cov)

#Now run the updated scGBM model
out <- scGBM::gbm.cell.covariate(Y,M=9,X.cov=X.cov,max.iter=30)

## First scGBM factor should be correlated with second factor
abs(cor(out$scores[,1], sim$V[,2])^2) |> print()

## And first scGBM factor should be uncorrelated with all estimated factors
apply(out$scores, 2, function(column) abs(cor(sim$V[,1], column))) |> print()
```

It's currently on a development branch, but if it works well for you I will integrate it into the main package!

**Comment by PierreBSC** [comment]
Dear Phillip,

Thanks a lot for your help and the time you spent working on the new function. The new function you designed perfectly worked and I could easily applied it to my dataset its large size (300K cells x 150 genes). Quite interestingly the fitting converged in way slower manner than without the covariate: after 50 iteration it has not converged yet while without it 10 iteration were enough, does that make sense to you ? 
In any case thanks a lot, if you are interested  I can send you the details of the fitting results !
Best,
Pierre
PS : As I am assuming that my covariate is a scaling factor that should impact the λ in a linear fashion I log-transformed the factor before using it, does that seem reasonable for you ?

**Comment by phillipnicol** [comment]
Hi Pierre,

Glad to hear that it is working! Adding a cell-specific covariate adds some complexity to the model, so it's not surprising that it may take a bit longer to converge. To assess convergence you can plot the objective function with 

```
plot(out$LL) #Here out is the scGBM object
```

you should see an "elbow" occur. I have seen many situations where I get the "max-iterations with no convergence warning" message but the final embedding is still adequate. 

As for log-transforming the covariate x_j, this would mean means x_j has a _multiplicative_ effect on lambda. The screenshot below writes out the model that is assumed when log(x_j) is used as a cell-specific covariate. In particular, a unit increase in x_j changes the mean expression of gene i by a multiplicative factor of a_i (where a_i is a learned coefficient). 


![Note Nov 30, 2024](https://github.com/user-attachments/assets/66c28172-f68e-4f35-bcab-1f1a826b22cf)

**Comment by PierreBSC** [comment]
Hi Philipp,

Thanks for the feedback. Indeed I did not get any early convergence stop but the log-likelihood progress plot seems to indicate a significantly slower convergence with the covariate. In any case thanks a lot for the script !
Best,
Pierre
